import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

import { GoogleAnalytics } from "@next/third-parties/google";

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000",
  ),
  title: {
    default: "Jomar Camacho | Frontend Developer",
    template: "%s | Jomar Camacho",
  },
  description:
    "Portafolio profesional de Jomar Camacho. Desarrollador Frontend especializado en React, Next.js y soluciones web escalables.",

  // Palabras clave para buscadores
  keywords: [
    "Desarrollador Web",
    "Frontend",
    "Full Stack",
    "React",
    "Next.js",
    "UI/UX",
    "Madrid",
  ],

  // Open Graph (Cómo se ve en redes sociales)
  openGraph: {
    title: "Jomar Camacho | Frontend Developer",
    description: "Transformo ideas en experiencias web de alto impacto.",
    url: process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000",
    siteName: "Jomar Camacho Portfolio",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Portfolio Preview",
      },
    ],
    locale: "es_ES",
    type: "website",
  },

  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title: "Jomar Camacho | Frontend Developer",
    images: ["/og-image.png"],
  },
};

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={bricolage.variable}>
      <body className="bg-gray-700">
        <Navbar />
        {children}
        <Footer />
      </body>

      {/* Carga Google Analytics solo si se ha proporcionado un ID de seguimiento */}
      {process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID ? (
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID} />
      ) : null}
    </html>
  );
}
